server:
  host: "0.0.0.0"
  port: ${WGREST_PORT}
  api_key: "${WGREST_API_KEY}"

database:
  type: "postgres"
  host: "${DB_HOST}"
  port: ${DB_PORT}
  name: "${DB_NAME}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"

interfaces:
  wg0:
    config_path: "/etc/wireguard/wg0.conf"
    subnet: "10.10.0.0/24"
    endpoint: "${SERVER_IP}:${WG0_PORT}"
    description: "FreeRADIUS clients"
  wg1:
    config_path: "/etc/wireguard/wg1.conf"
    subnet: "10.11.0.0/24"
    endpoint: "${SERVER_IP}:${WG1_PORT}"
    description: "MikroTik routers"

logging:
  level: "info"
  file: "/var/log/wgrest.log"