server:
  host: "0.0.0.0"
  port: "${WGREST_PORT}"
  api_key: "${WGREST_API_KEY}"

interfaces:
  wg0:
    config_path: "/etc/wireguard/wg0.conf"
    subnet: "${WG0_SUBNET}"
    endpoint: "${SERVER_IP}:${WG0_PORT}"
    description: "FreeRADIUS clients"
  wg1:
    config_path: "/etc/wireguard/wg1.conf"
    subnet: "${WG1_SUBNET}"
    endpoint: "${SERVER_IP}:${WG1_PORT}"
    description: "MikroTik routers"

logging:
  level: "info"
  file: "/var/log/wgrest.log"